"""
sumo_pack.py — build-pack generator for the SUMO24 MCP server.

Replaces the misguided zip-as-.sumo approach in sumo_compiler.py. Produces a
directory of artefacts the user feeds into SUMO24 GUI to obtain a real
.sumo project. Nothing in this module pretends to write a SUMO-loadable
file; every artefact has a clear, manual hand-off step documented in
BUILD_INSTRUCTIONS.md.

Inputs : a parsed schematic dict (from schematic_parser.parse_html / .parse_json)
Outputs: a directory <name>.sumo-pack/ containing:
    - plant.sumoslang        (compilable plant definition)
    - apply_parameters.scs   (SumoCore overrides — runs against the compiled DLL)
    - BUILD_INSTRUCTIONS.md  (step-by-step for the user)
    - schematic.json         (the source schematic, for traceability)
"""

from __future__ import annotations

import json
import os
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

# Re-use the existing schematic parser if available.
try:
    import schematic_parser as _sp
    _SP_AVAILABLE = True
except Exception:
    _sp = None
    _SP_AVAILABLE = False

try:
    from unit_type_registry import UNIT_TYPES as _UNIT_TYPES
    _UTR_AVAILABLE = True
except Exception:
    _UNIT_TYPES = {}
    _UTR_AVAILABLE = False

from difflib import get_close_matches


# ---------- Fail-fast schematic validation ------------------------------------

def validate_schematic(schematic: Dict[str, Any]) -> Dict[str, Any]:
    """
    Check that every unit type in the schematic is known to the registry.
    Returns {"ok": True} or {"ok": False, "errors": [...], "all_known_types": [...]}.
    Called by build_pack before any file is written so the failure is immediate
    rather than mid-generation.
    """
    errors: List[dict] = []
    known = set(_UNIT_TYPES.keys()) if _UTR_AVAILABLE else set()

    for u in schematic.get("units", []):
        t = u.get("type")
        if known and t not in known:
            hint = get_close_matches(t or "", known, n=1, cutoff=0.5)
            errors.append({
                "unit_id":   u.get("id"),
                "bad_type":  t,
                "suggestion": hint[0] if hint else None,
            })

    if not schematic.get("units"):
        errors.append({"issue": "schematic has no units"})

    if errors:
        return {"ok": False, "errors": errors,
                "all_known_types": sorted(known)}
    return {"ok": True}


# ---------- SumoSlang generation -------------------------------------------

def build_sumoslang(schematic: Dict[str, Any]) -> str:
    """
    Produce a compilable SumoSlang plant definition from a schematic.

    Emits a default kinetic model assignment for every reactor, valid class
    blocks for every supported unit type, and refuses to emit anything for
    units of unknown type.

    The output compiles in SUMO without hand-editing for the supported 23
    unit types. If a unit type is not supported, raises ValueError.
    """
    meta = schematic.get("meta", {})
    units = schematic.get("units", [])
    streams = schematic.get("streams", [])

    lines: List[str] = []
    lines.append(f"// SumoSlang generated by sumo_pack.py")
    lines.append(f"// Plant: {meta.get('plant_name', '')}")
    lines.append(f"// Design Q: {meta.get('design_flow_m3d', '?')} m3/d")
    lines.append(f"// Temperature: {meta.get('temperature_C', '?')} C")
    lines.append(f"// Generated: {datetime.utcnow().isoformat()}Z")
    lines.append("")
    lines.append("plant Plant {")
    lines.append("    kineticmodel ASM2d;   // default — change to ASM1/ASM3 if required")
    lines.append("")

    # Unit declarations
    for u in units:
        block = _sumoslang_unit_block(u)
        if block is None:
            raise ValueError(
                f"Unit {u.get('id')} has unsupported type '{u.get('type')}' "
                f"for SumoSlang generation"
            )
        for ln in block.splitlines():
            lines.append("    " + ln)
        lines.append("")

    # Stream declarations
    lines.append("    // Streams")
    for s in streams:
        lines.append(
            f"    stream {s['id']} "
            f"{{ from = {s['from']}; to = {s['to']}; type = {s['type']}; }}"
        )

    lines.append("}")
    return "\n".join(lines) + "\n"


def _sumoslang_unit_block(unit: Dict[str, Any]) -> "str | None":
    """
    Return a SumoSlang block string for one unit, or None if the type is
    not in the 23 supported types. Strings mirror Dynamita SumoSlang
    conventions for the unit types in unit_type_registry.py.
    """
    t = unit.get("type")
    uid = unit["id"]
    name = unit.get("name", uid)

    if t == "influent":
        return f'influent {uid} {{ name = "{name}"; }}'
    if t == "effluent":
        return f'effluent {uid} {{ name = "{name}"; }}'
    if t == "ras_flow":
        return f'effluent {uid} {{ name = "{name}"; role = ras_recycle; }}'
    if t == "was_flow":
        return f'effluent {uid} {{ name = "{name}"; role = was_outlet; }}'
    if t == "screen":
        return f'pointsettler {uid} {{ name = "{name}"; }}'
    if t == "grit_chamber":
        return f'pointsettler {uid} {{ name = "{name}"; role = grit_removal; }}'
    if t == "primary_clarifier":
        return f'primaryclarifier {uid} {{ name = "{name}"; }}'
    if t in ("anaerobic_zone", "anoxic_zone", "aerobic_zone"):
        return f'cstr {uid} {{ name = "{name}"; }}'
    if t == "oxidation_ditch":
        return f'cstr {uid} {{ name = "{name}"; loop = true; }}'
    if t == "mbbr":
        return f'biofilmcstr {uid} {{ name = "{name}"; }}'
    if t == "secondary_clarifier":
        return f'settler1d {uid} {{ name = "{name}"; }}'
    if t in ("tertiary_filter", "disinfection", "dewatering"):
        return f'pointsettler {uid} {{ name = "{name}"; }}'
    if t in ("ras_pump", "was_pump", "internal_recycle"):
        return f'pump {uid} {{ name = "{name}"; }}'
    if t == "thickener":
        return f'thickener {uid} {{ name = "{name}"; }}'
    if t == "anaerobic_digester":
        return f'digester {uid} {{ name = "{name}"; }}'
    if t == "splitter":
        return f'splitter {uid} {{ name = "{name}"; }}'
    if t == "sludge_splitter":
        return f'sludgesplitter {uid} {{ name = "{name}"; }}'
    if t == "combiner":
        return f'combiner {uid} {{ name = "{name}"; }}'
    return None


def validate_sumoslang(text: str) -> Dict[str, Any]:
    """
    Lightweight syntactic lint on a SumoSlang text. Does NOT replace SUMO's
    own compiler, but catches the most common breakages so we never emit a
    pack with obvious problems.
    """
    errors: List[str] = []
    warnings: List[str] = []

    if "plant " not in text:
        errors.append("no `plant` block declared")
    if "kineticmodel " not in text:
        warnings.append("no `kineticmodel` line — SUMO will use its default")
    if "{{ " in text or "}}" in text:
        errors.append("unbalanced braces in template substitution — generation bug")
    if "TODO" in text or "FIXME" in text:
        errors.append("placeholder markers in output — generation incomplete")

    # Every opened brace must close
    open_count = text.count("{")
    close_count = text.count("}")
    if open_count != close_count:
        errors.append(
            f"brace mismatch: {open_count} '{{' vs {close_count} '}}'"
        )

    return {"ok": not errors, "errors": errors, "warnings": warnings}


# ---------- .scs override script -------------------------------------------

def build_apply_scs(schematic: Dict[str, Any]) -> str:
    """
    Produce a SumoCore script that applies every schematic parameter to a
    compiled, loaded plant. Re-uses schematic_parser's command builder if
    available.
    """
    if _SP_AVAILABLE and hasattr(_sp, "build_command_lines"):
        return _sp.build_command_lines(schematic)
    # Fallback: build inline.
    lines = ['load "state.xml";']
    for u in schematic.get("units", []):
        for p in u.get("parameters", []):
            sv = p.get("sumo_variable")
            if sv:
                desc = u["id"] + " " + p.get("description", "")
                lines.append(f"set {sv} {p['value']};   // {desc}")
    lines += ["mode steady;", "start;"]
    return "\n".join(lines) + "\n"


# ---------- Build pack writer ----------------------------------------------

_BUILD_INSTRUCTIONS = """\
# Build Instructions

This directory is a **build pack**, not a `.sumo` file. SUMO24 cannot be
asked to open it directly. Follow the 5 steps below to turn it into a
working SUMO24 project.

## 1. Create a new SUMO24 project

In SUMO24 GUI: **File → New Project**. Save the empty project as
`{stem}.sumo` somewhere convenient.

## 2. Define the plant topology

Open the SumoSlang editor (**Edit → Plant Definition** or the SumoSlang
panel, depending on your SUMO version) and paste the contents of:

    plant.sumoslang

Click **Compile**. If compilation fails, the line number in SUMO's error
message points directly into `plant.sumoslang`. Fix and recompile.

## 3. Save initial state

Click **Simulate → Initialize**. Once SUMO reports "Ready for simulation":

    Advanced → Core Window
    > maptoic; save "state.xml";

## 4. Apply parameter overrides

Still in the Core Window, paste the contents of:

    apply_parameters.scs

This applies every parameter from the source schematic. Re-save:

    save "state.xml";

## 5. Hand off to the MCP server

Copy `state.xml` and `sumoproject.dll` (which SUMO created next to
`{stem}.sumo` during compile) into the MCP project root:

    F:/UNI/SUMO/MCP/state.xml
    F:/UNI/SUMO/MCP/sumoproject.dll

The MCP server's `validate_sumo_environment` should now return all green,
and `run_steady_state` should run against the new plant.
"""


def build_pack(
    schematic: Dict[str, Any],
    output_dir: "str | Path",
    overwrite: bool = False,
) -> Dict[str, Any]:
    """
    Write a build pack to `output_dir`. Returns a summary dict.

    Raises:
        FileExistsError  if output_dir exists and overwrite=False.
        ValueError       if the schematic is empty or SumoSlang lint fails.
    """
    # Fail-fast: validate all unit types before creating any files.
    v = validate_schematic(schematic)
    if not v["ok"]:
        return {"ok": False, "stage": "validate", **v}

    output_dir = Path(output_dir)
    stem = output_dir.stem.replace(".sumo-pack", "") or "plant"

    if not schematic.get("units"):
        raise ValueError("Schematic has no units — nothing to build")

    if output_dir.exists():
        if not overwrite:
            raise FileExistsError(
                f"{output_dir} already exists; pass overwrite=True to replace"
            )
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # 1. SumoSlang
    slang = build_sumoslang(schematic)
    lint = validate_sumoslang(slang)
    if not lint["ok"]:
        raise ValueError(f"Generated SumoSlang failed lint: {lint['errors']}")

    (output_dir / "plant.sumoslang").write_text(slang, encoding="utf-8")

    # 2. .scs
    (output_dir / "apply_parameters.scs").write_text(
        build_apply_scs(schematic), encoding="utf-8"
    )

    # 3. README
    (output_dir / "BUILD_INSTRUCTIONS.md").write_text(
        _BUILD_INSTRUCTIONS.format(stem=stem), encoding="utf-8"
    )

    # 4. schematic.json for traceability
    (output_dir / "schematic.json").write_text(
        json.dumps(schematic, indent=2), encoding="utf-8"
    )

    return {
        "ok": True,
        "output_dir": str(output_dir),
        "files": [p.name for p in sorted(output_dir.iterdir())],
        "units": len(schematic.get("units", [])),
        "streams": len(schematic.get("streams", [])),
        "sumoslang_lint": lint,
        "next_step": (
            f"Open {output_dir / 'BUILD_INSTRUCTIONS.md'} and follow the "
            "5-step procedure to build the SUMO project inside SUMO24 GUI."
        ),
    }


# ---------- Apply schematic to a verified baseline (Tier 1) ---------------

def apply_to_baseline(
    schematic: Dict[str, Any],
    baseline_sumo: "str | Path",
    baseline_dll: "str | Path",
    output_sumo: "str | Path",
    *,
    strict: bool = True,
) -> Dict[str, Any]:
    """
    Tier 1 path: copy a known-good (.sumo + .dll) pair to a new location,
    then apply every parameter override from the schematic via SumoCore.

    This does NOT change topology — only parameter values. If strict=True
    (default), refuses when any schematic parameter does not resolve to a
    variable present in the baseline's state.xml.
    """
    baseline_sumo = Path(baseline_sumo)
    baseline_dll = Path(baseline_dll)
    output_sumo = Path(output_sumo)

    if not baseline_sumo.exists():
        raise FileNotFoundError(f"baseline_sumo not found: {baseline_sumo}")
    if not baseline_dll.exists():
        raise FileNotFoundError(f"baseline_dll not found: {baseline_dll}")

    # 1. Copy the verified pair to the output location.
    output_sumo.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(baseline_sumo, output_sumo)
    shutil.copy2(baseline_dll, output_sumo.parent / "sumoproject.dll")

    # 2. Collect every parameter override from the schematic.
    overrides: List[tuple] = []
    for u in schematic.get("units", []):
        for p in u.get("parameters", []):
            sv = p.get("sumo_variable")
            if sv:
                overrides.append((sv, float(p["value"]), u["id"]))

    # 3. Resolve against the baseline's state.xml.
    state_xml = output_sumo.parent / "state.xml"
    known_vars = _read_state_variable_names(state_xml) if state_xml.exists() else set()

    resolved, unresolved = [], []
    for sv, val, uid in overrides:
        if not known_vars or sv in known_vars:
            resolved.append((sv, val, uid))
        else:
            unresolved.append((sv, uid))

    if strict and unresolved:
        return {
            "ok": False,
            "reason": "schematic references variables not in baseline",
            "unresolved": unresolved[:20],
            "unresolved_count": len(unresolved),
            "hint": (
                "Either change the baseline, edit the schematic to match it, "
                "or call apply_schematic_to_baseline with strict=false to apply "
                "only the subset that resolves."
            ),
        }

    # 4. Write the overrides into state.xml using the server's persistence
    #    helper if available; otherwise fall back to a .scs script.
    try:
        from server import _persist_parameters_into_state_xml  # type: ignore
        _persist_parameters_into_state_xml(state_xml, resolved)
        return {
            "ok": True,
            "mode": "persisted",
            "output_sumo": str(output_sumo),
            "applied": len(resolved),
            "skipped": len(unresolved),
        }
    except Exception as e:
        scs_path = output_sumo.parent / "apply_overrides.scs"
        scs_path.write_text(
            "\n".join(f"set {sv} {val};" for sv, val, _ in resolved) + "\n",
            encoding="utf-8",
        )
        return {
            "ok": True,
            "mode": "scs_fallback",
            "output_sumo": str(output_sumo),
            "apply_script": str(scs_path),
            "applied": len(resolved),
            "skipped": len(unresolved),
            "note": (
                f"In-process persist failed ({e!s}); applied overrides written "
                f"to {scs_path.name} for manual application in SUMO Core Window."
            ),
        }


def _read_state_variable_names(state_xml: Path) -> set:
    """Return the set of variable names declared in a SUMO state.xml."""
    import xml.etree.ElementTree as ET
    try:
        tree = ET.parse(state_xml)
    except ET.ParseError:
        return set()
    return {el.get("name") for el in tree.iter() if el.get("name")}
